apiVersion: v1
kind: PersistentVolume
metadata:
  name: controllerbase-logs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2000Mi
  local:
    path: /storage/controllerbase/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pdd-dev-app01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controllerbase-logs-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Mi
  storageClassName: local-storage
  volumeName: controllerbase-logs-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: controllerbase-app-csv-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2000Mi
  local:
    path: /storage/csv/controllerbase-app
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pdd-dev-app01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controllerbase-app-csv-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Mi
  storageClassName: local-storage
  volumeName: controllerbase-app-csv-pv